# Generated by Django 4.1.7 on 2023-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0008_task_minutes_to_task_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='minutes_to_task_start',
            field=models.DurationField(null=True),
        ),
    ]
