# Generated by Django 4.1.7 on 2023-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0010_alter_task_minutes_to_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
