# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - final-to-do

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_20deb7a2d43f4553848b1264ca2e6db6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_53fb47f527d447a7b262c854e9bbda9c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_20deb7a2d43f4553848b1264ca2e6db6 }}/bamwesigyecalvinkiiza/final:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'final-to-do'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8692454293cb4533a5ba09be29eb7e65 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_20deb7a2d43f4553848b1264ca2e6db6 }}/bamwesigyecalvinkiiza/final:${{ github.sha }}'